; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[global]
board_build.partitions = partitions_custom.csv

[common_env_data]
build_flags =
; Define to print debug output to Serial0
	-D SERIAL_OUT
; Define to use onboard LED signaling (along with LED pin number)
	;-D USELED=48
; Define dual core support
  -D DUALCORE
; Enable "unused variable" warnings as errors
	-Werror=unused-variable

; Library dependencies
lib_deps = 
	knolleary/PubSubClient@^2.8
	dojyorin/base64_encode@^2.0.4
	tobiasschuerg/ESP8266 Influxdb@^3.13.2
	bblanchon/ArduinoJson@^6.18.5
  h2zero/NimBLE-Arduino@^2.3.1

[platformio]
; Default Env Selection
default_envs = esp32dev-01

[env:esp32-S3-N16R8] 			;ESP32-S3 with 16MB flash and 8MB PSRAM S3-DevKitC-1 (bezeichnung bei Amazon: ESP32-S3-DevKitC-1-N16R8)
platform = espressif32 @ 6.12.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.extra_flags = 
  -DBOARD_HAS_PSRAM

lib_deps = 
	${common_env_data.lib_deps}
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_port = COM7
upload_speed = 921600
test_port = COM5
test_speed = 921600
monitor_port = COM7
build_flags = 
	-D DEVICENAME=\"51210122C200448\"
  -D CLTNAME=jk-bt-mqtt-01
	${common_env_data.build_flags}

[env:esp32dev-01]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	${common_env_data.lib_deps}
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_port = COM4
monitor_port = COM4
board_build.partitions = partitions_custom.csv
build_flags = 
	-D DEVICENAME=\"51210122C200448\"
  -D CLTNAME=jk-bt-mqtt-01
	${common_env_data.build_flags}

[env:esp32dev-02]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	${common_env_data.lib_deps}
monitor_speed = 115200
upload_port = COM6
monitor_port = COM6
board_build.partitions = partitions_custom.csv
build_flags = 
	-D DEVICENAME=\"JK-PB2A16S20P-00\"
  -D CLTNAME=jk-bt-mqtt-00
  ${common_env_data.build_flags}

[env:esp32dev-debug]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	${common_env_data.lib_deps}
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
board_build.partitions = partitions_custom.csv
build_flags = 
	-D DEVICENAME=\"JK-PB2A16S20P-TEST\"
    -D CLTNAME=jk-bt-mqtt-test
    ${common_env_data.build_flags}
