; PlatformIO Project Configuration Override File
;   Changes done here override settings in platformio.ini
;
; *****************************************************************************
; ***  to activate copy this file and rename it to platformio_override.ini  ***
; *****************************************************************************
;
; Please visit documentation for the options and examples
; http://docs.platformio.org/en/stable/projectconf.html

[platformio]
; Default Env Selection
default_envs = jk-bms-00

[env:jk-bms-00]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	${common_env_data.lib_deps}
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
board_build.partitions = partitions_custom.csv
build_flags = 
	-D DEVICENAME=\"JK-PB2A16S20P-00\"
    -D CLTNAME=jk-bms-00
    ${common_env_data.build_flags}

[env:jk-bms-01]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	${common_env_data.lib_deps}
monitor_speed = 115200
upload_port = COM6
monitor_port = COM6
board_build.partitions = partitions_custom.csv
build_flags = 
	-D DEVICENAME=\"JK-PB2A16S20P-01\"
    -D CLTNAME=jk-bms-01
    ${common_env_data.build_flags}